### ISSUE TITLE
Adicionar nova cidade

### ISSUE THREAD

**Issue by vvaz** [Marianassalmeida/flag1#1]
Podes adicionar uma nova cidade?

Talvez Leiria?

**Comment by Marianassalmeida** [comment]
Claro que sim! Trato disso amanhã ao final do dia.

**Comment by vvaz** [comment]
Depois na mensagem da commit podes por "fixes #1" e isso deverá fechar este issue automaticamente.

**Comment by vvaz** [comment]
Ou então podes fechar com um comentário clicando neste botão:

![imagem](https://github.com/Marianassalmeida/flag1/assets/89161/1c3da74b-c3fe-40ed-b687-fa664a711c0f)
